# .github/workflows/push-dist.yml

name: Push dist

on:
  push:
    branches:
      - main

jobs:
  push-dist:
    name: Push dist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install -g @angular/cli@latest && npm install --legacy-peer-deps
      - uses: kategengler/put-built-npm-package-contents-on-branch@v1.0.0
        with:
          branch: build
          token: ${{ secrets.GITHUB_TOKEN }}
